
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS dogs CASCADE;
DROP TABLE IF EXISTS walks-dogs CASCADE;
DROP TABLE IF EXISTS walks CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE dogs (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  avatar VARCHAR(255) NOT NULL
);

CREATE TABLE walks-dogs (
  id SERIAL PRIMARY KEY NOT NULL,
  dog_id  INTEGER REFERENCES dogs(id) ON DELETE CASCADE,
  walk_id  INTEGER REFERENCES walks(id) ON DELETE CASCADE,
);

CREATE TABLE walks (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id  INTEGER REFERENCES users(id) ON DELETE CASCADE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  payed_for BOOLEAN NOT NULL DEFAULT FALSE,
  availible_spots INTEGER NOT NULL DEFAULT 12
);
