
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS walks CASCADE;
DROP TABLE IF EXISTS dogs CASCADE;
DROP TABLE IF EXISTS days CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE days (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  date DATE NOT NULL
);

CREATE TABLE dogs (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  avatar VARCHAR(255) NOT NULL
);

CREATE TABLE walks (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id  INTEGER REFERENCES users(id) ON DELETE CASCADE,
  dog_id  INTEGER REFERENCES dogs(id) ON DELETE CASCADE,
  day_id INTEGER REFERENCES days(id) ON DELETE CASCADE,
  payed_for BOOLEAN NOT NULL DEFAULT FALSE,
  availible_spots INTEGER NOT NULL DEFAULT 12
);
